var webpack = require('webpack');

var HtmlWebpackPlugin = require('html-webpack-plugin');

var defaults = require('./webpack.config.common')
var config = Object.create(defaults.config);
var PATHS = defaults.paths

const HOST = process.env.HOST || "localhost";
const PORT = process.env.PORT || "3000";

Object.assign(config, {

	entry: [
		`webpack-dev-server/client?http://${HOST}:${PORT}`, // WebpackDevServer host and port
		`webpack/hot/only-dev-server`,
		PATHS.entry // Your appʼs entry point
	],
	devtool: process.env.WEBPACK_DEVTOOL || 'eval-source-map',
	module: {
		loaders: [
			{
				test: /\.jsx?$/,
				exclude: /(node_modules|bower_components)/,
				loaders: ['babel'],
			},
			{
				test: /\.css$/,
				loader: 'style!css!postcss'
			},
			{
				test: /\.less$/,
				loader: 'style!css!postcss!less'
			}
		].concat(require('./webpack.config.loaders'))
	},
	devServer: {
		contentBase: PATHS.build,
		noInfo: true,
		hot: true,
		inline: false,
		historyApiFallback: true,
		port: PORT,
		host: HOST
	},
	plugins: [
		new webpack.NoErrorsPlugin(),
		new webpack.HotModuleReplacementPlugin(),
		new HtmlWebpackPlugin({
	        template: PATHS.index, // Move the index.html file
	        inject: true // inject all files that are generated by webpack, e.g. bundle.js, main.css with the correct HTML tags
	    })
	]

})

module.exports = config